### ISSUE TITLE
Assets: LICENSE 및 저작권

### ISSUE THREAD

**Issue by login-dhcp** [PortalCube/shany-anim-viewer#1]
Asset들 관련 라이센스를 추가해야 할 것 같습니다.

저작권 문제도 좀 걸려서 따로 배포하거나, 최소한 이 레포에서는 빼 두는게 어떨까 싶네요 :)

**Comment by PortalCube** [comment]
애셋은 용량 문제도 있고 해서 빼는 쪽으로 생각하고 있는데 지금은 뾰족한 수가 없네요.. 어떤식으로 배포하면 좋을지 좀 고민하고 있습니다

**Comment by PortalCube** [comment]
@login-dhcp 좀 생각해봤는데.. 샤니위키에 올린 스파인 뷰어 애셋으로 주소를 바꾸고 이쪽 애셋을 내리면 괜찮을 것 같은데 혹시 샤니위키 리소스를 사용해도 괜찮을까요?

**Comment by login-dhcp** [comment]
예 큰 문제 없습니다.   

이 레포 readme에 에셋들 압축 파일 달아주시면 샤니위키쪽 서버로 업로드하겠습니다. 
당분간은 readme에 링크를 달고 업데이트시 연락 주시면 수동으로 업데이트하는 방향으로 진행하면 좋을 것 같네요 :) 

지향점은 샤니위키 자체에 각 리소스롤 올리는 것이라고 생각합니다. 
https://shinycolors.wiki/wiki/Mano_Sakuragi/Gallery 에 각 asset 파일까지 있는 정도를 생각하고 있습니다.
이 경우에는 위키 통해서 파일 추가 업로드/갱신하면 충분하니 프로젝트에 있어서 드는 품을 줄일 수 있지 않을까 싶어요

**Comment by PortalCube** [comment]
#2 에서 수정 완료

**Comment by PortalCube** [comment]
@login-dhcp 니치카, 미코토, 루카의 데이터를 추가했으니 시간 되실 때 업데이트 부탁드립니다!
애셋 데이터는 Release 탭의 0.4.2에 첨부해두었습니다.

**Comment by login-dhcp** [comment]
넵 업데이트하였으니 확인 부탁드립니다!

**Comment by PortalCube** [comment]
잘 적용되었네요! 감사합니다 👍
